tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tsc_dbt_db
      schema: dev
      warehouse: compute_wh
      threads: 8
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: tsc_dbt_db
      schema: prod
      warehouse: compute_wh
      threads: 8
